services:
  backend:
    build: ./backend
    ports: # hote:container
      - 12345:3000
    volumes:
      - ./backend/src/:/app/src/

  frontend:
    build: ./frontend
    ports: # hote:container
      - 23456:5173
    volumes:
      - ./frontend/src/:/app/src/
